Repository Programming-Engineering-Pmi-33/Music-Quiz, pull requests merged in 2020-10, with the labels that each got.

#16 Feature 13 configure test project
  .gitignore
  DbTestProject/DbTestProject.csproj
  DbTestProject/DbTestProject.sln
  DbTestProject/Models/TestModel.cs
  DbTestProject/Program.cs
  DbTestProject/TestDbContext.cs
Labels: good first issue

#18 added functions to fill the database with test data
  DbTestProject/Models/Score.cs
  DbTestProject/Program.cs
  DbTestProject/TestDbContext.cs
Labels: enhancement

#30 Remove foreign key annotations
  sandbox/DbTestProject/Models/Quiz.cs
  sandbox/DbTestProject/Models/QuizSong.cs
Labels: invalid

#29 Add script and Readme file for TestDbProject
  sandbox/DbTestProject/README.md
  sandbox/DbTestProject/update-database.sh
Labels: documentation

#35 #27 change models
  sandbox/DbTestProject/Models/Genre.cs
  sandbox/DbTestProject/Models/Quiz.cs
  sandbox/DbTestProject/Models/Score.cs
  sandbox/DbTestProject/Models/Song.cs
  sandbox/DbTestProject/Models/User.cs
  sandbox/DbTestProject/Program.cs
  sandbox/DbTestProject/TestDbContext.cs
Labels: bug
